
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ru.innopolis.comicon.parser;

/** CUP generated interface containing symbol constants. */
public interface MySymbol {
  /* terminals */
  public static final int BOOLEANLITERAL = 26;
  public static final int IS = 4;
  public static final int CLASS = 2;
  public static final int ELSE = 13;
  public static final int RPAREN = 16;
  public static final int THEN = 12;
  public static final int INTEGERLITERAL = 24;
  public static final int WHILE = 9;
  public static final int LOOP = 10;
  public static final int IDENTIFIER = 23;
  public static final int END = 5;
  public static final int RETURN = 14;
  public static final int REALLITERAL = 25;
  public static final int IF = 11;
  public static final int COLON = 21;
  public static final int LBRACKET = 17;
  public static final int LPAREN = 15;
  public static final int THIS = 8;
  public static final int COMMA = 19;
  public static final int EOF = 0;
  public static final int METHOD = 7;
  public static final int DOT = 20;
  public static final int error = 1;
  public static final int ASSIGN = 22;
  public static final int RBRCKET = 18;
  public static final int EXTENDS = 3;
  public static final int VAR = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "EXTENDS",
  "IS",
  "END",
  "VAR",
  "METHOD",
  "THIS",
  "WHILE",
  "LOOP",
  "IF",
  "THEN",
  "ELSE",
  "RETURN",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRCKET",
  "COMMA",
  "DOT",
  "COLON",
  "ASSIGN",
  "IDENTIFIER",
  "INTEGERLITERAL",
  "REALLITERAL",
  "BOOLEANLITERAL"
  };
}

